name: calculadora
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
